// ─────────────────────────────────────────────────────────
// ETAP 7.5 — Scenarios: A. PROCUREMENT OPERATIONS (20)
// ─────────────────────────────────────────────────────────

import type { AdvisoryScenario } from "../types/index";
import { makeSessionState, makePageContext } from "../types/index";

export const A_PROCUREMENT_OPERATIONS: AdvisoryScenario[] = [
  {
    id: "A-001",
    category: "A-procurement-operations",
    title: "Supplier price increase — no justification",
    description: "Buyer receives 15% price increase letter from key supplier. No cost breakdown provided.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U1", maturity: "developing", intentConfidence: 0.8 }),
    turns: [
      {
        user: "Dostawca przysłał pismo o podwyżce cen o 15% od następnego kwartału. Nie dał żadnego uzasadnienia. Co mam zrobić?",
        expectedKeywords: ["uzasadnienie", "koszty", "dane", "benchmark", "odpowiedź", "analizę"],
        forbiddenPhrases: ["Świetne pytanie", "chętnie pomogę", "oczywiście"],
        expectsDiagnosticQuestion: true,
      },
      {
        user: "To strategiczny dostawca, prawie 30% naszego spend w tej kategorii. Kontrakt kończy się za 8 miesięcy.",
        expectedKeywords: ["zależność", "alternatyw", "BATNA", "jednoźródłow", "benchmark", "negocjacj"],
        forbiddenPhrases: ["Rozumiem", "to trudna sytuacja", "warto rozważyć"],
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Nie mamy żadnych benchmarków dla tej kategorii i nigdy wcześniej nie negocjowaliśmy z nimi twardziej.",
        expectedKeywords: ["should-cost", "analiz", "przygotowanie", "danych", "powinien", "negocjacj"],
        expectsEscalation: true,
        forbiddenPhrases: ["może spróbować", "warto pomyśleć"],
      },
    ],
    expectedIntent: "I8_NEGOTIATIONS",
    expectedUrgency: "U1",
    expectedEscalation: true,
    expectedCapabilities: ["Should-Cost Analysis", "Negotiation Preparation"],
    tags: ["supplier-increase", "price-increase", "U1", "strategic-supplier"],
  },
  {
    id: "A-002",
    category: "A-procurement-operations",
    title: "Inflation pressure — multiple categories",
    description: "Buyer faces simultaneous price increases across 6 categories citing general inflation.",
    locale: "pl",
    pageSlug: "services/analiza-spot",
    pageContext: makePageContext("services/analiza-spot", "I1_SAVINGS"),
    sessionState: makeSessionState({ detectedIntent: "I1_SAVINGS", urgency: "U1", maturity: "reactive" }),
    turns: [
      {
        user: "Mamy podwyżki od dostawców w 6 kategoriach jednocześnie. Wszyscy powołują się na inflację. Nasz CFO pyta o wpływ na marżę.",
        expectedKeywords: ["inflacja", "marż", "kategorii", "benchmark", "analiz", "cost breakdown", "uzasadnienie"],
        forbiddenPhrases: ["to normalne w obecnych czasach", "inflacja jest realna"],
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Skala podwyżek to łącznie około 2.3 mln PLN rocznie na spend 18 mln. Mamy na to maks. 6 tygodni.",
        expectedKeywords: ["priorytet", "szybk", "SPOT", "diagnostic", "analiz", "kategorii"],
        expectsEscalation: true,
      },
    ],
    expectedIntent: "I1_SAVINGS",
    expectedUrgency: "U1",
    expectedEscalation: true,
    expectedCapabilities: ["SPOT Analysis", "Should-Cost Analysis"],
    tags: ["inflation", "multi-category", "CFO-pressure", "U1"],
  },
  {
    id: "A-003",
    category: "A-procurement-operations",
    title: "No spend visibility",
    description: "Company has spend scattered across 4 ERPs, 3 countries, 12 cost centers. Nobody knows what they're buying.",
    locale: "pl",
    pageSlug: "services/spend-analytics",
    pageContext: makePageContext("services/spend-analytics", "I2_FORECASTING"),
    sessionState: makeSessionState({ detectedIntent: "I2_FORECASTING", urgency: "U2", maturity: "reactive" }),
    turns: [
      {
        user: "Mamy 4 systemy ERP i zakupy w 3 krajach. Nikt nie wie ile dokładnie wydajemy i na co. Jak zacząć?",
        expectedKeywords: ["spend cube", "danych", "widoczność", "kategorii", "analityk", "konsolidacj"],
        forbiddenPhrases: ["trzeba zacząć od", "po prostu"],
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Mamy 8500 aktywnych dostawców. Nie wiemy który jest strategiczny, a który jednorazowy.",
        expectedKeywords: ["segmentacja", "dostawcó", "Pareto", "spend analytic", "widoczność"],
        expectsEscalation: true,
      },
    ],
    expectedIntent: "I2_FORECASTING",
    expectedUrgency: "U2",
    tags: ["spend-visibility", "ERP", "multi-country", "data-chaos"],
  },
  {
    id: "A-004",
    category: "A-procurement-operations",
    title: "Procurement chaos — pure firefighting mode",
    description: "Procurement team of 3 people serving 600 requests/month. No processes, no categories, everything urgent.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "I5_SOURCING"),
    sessionState: makeSessionState({ detectedIntent: "I5_SOURCING", urgency: "U2", maturity: "reactive" }),
    turns: [
      {
        user: "Mój zespół zakupowy to 3 osoby i obsługują 600 zapytań miesięcznie. Żadnych procesów, żadnych kategorii, wszystko pilne. Od czego zacząć?",
        expectedKeywords: ["proces", "priorytet", "kategorii", "model", "transformacj", "diagram"],
        forbiddenPhrases: ["trzeba po prostu", "warto rozważyć wdrożenie"],
        expectsDiagnosticQuestion: true,
      },
      {
        user: "CEO oczekuje 10% oszczędności w tym roku. Mój zespół nie ma nawet czasu na przegląd kontraktów.",
        expectedKeywords: ["priorytety", "kategorii", "oszczędności", "szybk", "SPOT", "zakres"],
        expectsEscalation: true,
      },
    ],
    expectedIntent: "I5_SOURCING",
    tags: ["firefighting", "team-capacity", "CEO-pressure"],
  },
  {
    id: "A-005",
    category: "A-procurement-operations",
    title: "No category strategy",
    description: "Company buys reactively, no category plans, suppliers propose prices with no pushback.",
    locale: "pl",
    pageSlug: "services/strategia-kategorii",
    pageContext: makePageContext("services/strategia-kategorii", "I5_SOURCING"),
    sessionState: makeSessionState({ detectedIntent: "I5_SOURCING", urgency: "U2", maturity: "reactive" }),
    turns: [
      {
        user: "Nie mamy żadnej strategii kategorii. Kupujemy reaktywnie — dostawca proponuje cenę, my akceptujemy. Jak to zmienić?",
        expectedKeywords: ["strategia kategorii", "spend", "rynk", "benchmark", "negocjacj", "kategori"],
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Kategorie krytyczne to energetyka, opakowania i logistyka. Łącznie 40 mln PLN rocznie.",
        expectedKeywords: ["priorytet", "energetyk", "opakowania", "logistyk", "should-cost", "potencjał"],
        expectsEscalation: true,
      },
    ],
    expectedIntent: "I5_SOURCING",
    tags: ["category-strategy", "reactive-buying"],
  },
  {
    id: "A-006",
    category: "A-procurement-operations",
    title: "Budget overrun — procurement blamed",
    description: "Finance has flagged procurement as main cause of 8% budget overrun. CPO under pressure.",
    locale: "pl",
    pageSlug: "services/analiza-spot",
    pageContext: makePageContext("services/analiza-spot", "I1_SAVINGS"),
    sessionState: makeSessionState({ detectedIntent: "I1_SAVINGS", urgency: "U1", maturity: "developing" }),
    turns: [
      {
        user: "Finanse oskarżają zakupy o przekroczenie budżetu o 8%. CPO jest pod presją zarządu. Potrzebujemy szybko odpowiedzi — skąd przekroczenie i jak to naprawić.",
        expectedKeywords: ["analiz", "spend", "kategorii", "dane", "korzeni", "szybk"],
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Największe przekroczenia są w energetyce i usługach utrzymania. Mamy 3 tygodnie do prezentacji dla zarządu.",
        expectedKeywords: ["SPOT", "priorytet", "szybk", "analiz", "zarząd", "prezentacj"],
        expectsEscalation: true,
      },
    ],
    expectedIntent: "I1_SAVINGS",
    expectedUrgency: "U1",
    tags: ["budget-overrun", "board-pressure", "U1"],
  },
  {
    id: "A-007",
    category: "A-procurement-operations",
    title: "Single source dependency — critical component",
    description: "Only one approved supplier for a production-critical component. Supplier knows this.",
    locale: "pl",
    pageSlug: "services/zarzadzanie-ryzykiem",
    pageContext: makePageContext("services/zarzadzanie-ryzykiem", "I3_SUPPLIER_RISK"),
    sessionState: makeSessionState({ detectedIntent: "I3_SUPPLIER_RISK", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Mamy jednego dostawcę na krytycznym komponencie produkcyjnym. On to wie i systematycznie podnosi ceny. Co zrobić?",
        expectedKeywords: ["alternatyw", "kwalifikacj", "BATNA", "ryzyko", "jednoźródłow", "dywersyf"],
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Czas kwalifikacji nowego dostawcy to minimum 18 miesięcy. Podwyżka wchodzi w życie za 4 miesiące.",
        expectedKeywords: ["most negotiation", "przejściow", "umow", "warunki", "kontrak", "równolegle"],
        expectsEscalation: true,
      },
    ],
    expectedIntent: "I3_SUPPLIER_RISK",
    tags: ["single-source", "supplier-dependency", "risk"],
  },
  {
    id: "A-008",
    category: "A-procurement-operations",
    title: "Low negotiation confidence",
    description: "Procurement manager admits team has never done structured negotiation. Upcoming renewal.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "reactive" }),
    turns: [
      {
        user: "Mój zespół nigdy nie prowadził ustrukturyzowanych negocjacji. Wszystko było na poziomie osobistych relacji. Za 3 miesiące mamy odnowienie 5 głównych kontraktów.",
        expectedKeywords: ["przygotowanie", "dane", "trening", "warsztat", "negocjacj", "benchmark"],
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Łączna wartość kontraktów to ok. 12 mln PLN. Nasz dostawcy też wiedzą, że jesteśmy do nich przywiązani.",
        expectedKeywords: ["potencjał", "przygotowanie", "analiz", "warsztat", "Harvard", "dane"],
        expectsEscalation: true,
      },
    ],
    expectedIntent: "I8_NEGOTIATIONS",
    tags: ["low-confidence", "negotiation-readiness", "contract-renewal"],
  },
  {
    id: "A-009",
    category: "A-procurement-operations",
    title: "Procurement transformation — where to start",
    description: "New CPO joining company. Wants to transform procurement from tactical to strategic in 18 months.",
    locale: "pl",
    pageSlug: "services/transformacja",
    pageContext: makePageContext("services/transformacja", "I5_SOURCING"),
    sessionState: makeSessionState({ detectedIntent: "I5_SOURCING", urgency: "U2", maturity: "developing", buyingStage: "consideration" }),
    turns: [
      {
        user: "Właśnie dołączyłem jako nowy CPO. Firma ma 200 mln PLN spend, reaktywny dział zakupów i brak danych. Mam 18 miesięcy na transformację. Od czego zacząć?",
        expectedKeywords: ["diagnoza", "spend", "widoczność", "priorytet", "quick wins", "kategorii", "maturity"],
        expectsDiagnosticQuestion: true,
      },
    ],
    expectedIntent: "I5_SOURCING",
    tags: ["CPO-onboarding", "transformation", "strategic"],
  },
  {
    id: "A-010",
    category: "A-procurement-operations",
    title: "Spend analytics need — no system",
    description: "Company manually exports from SAP to Excel and builds reports weekly. Not scalable.",
    locale: "pl",
    pageSlug: "services/spend-analytics",
    pageContext: makePageContext("services/spend-analytics", "I2_FORECASTING"),
    sessionState: makeSessionState({ detectedIntent: "I2_FORECASTING", urgency: "U3", maturity: "reactive" }),
    turns: [
      {
        user: "Robimy eksporty z SAP do Excela co tydzień i ręcznie budujemy raporty spend. To zajmuje 2 dni robocze. Jak to zautomatyzować i zinterpretować dane?",
        expectedKeywords: ["spend cube", "analityk", "automatyzacj", "kategori", "dashboar", "danych"],
        expectsDiagnosticQuestion: true,
      },
    ],
    expectedIntent: "I2_FORECASTING",
    tags: ["spend-analytics", "manual-process", "SAP"],
  },
  {
    id: "A-011",
    category: "A-procurement-operations",
    title: "Should-cost analysis inquiry",
    description: "Buyer wants to understand if they're overpaying. Doesn't know how to challenge supplier.",
    locale: "pl",
    pageSlug: "services/should-cost",
    pageContext: makePageContext("services/should-cost", "I1_SAVINGS"),
    sessionState: makeSessionState({ detectedIntent: "I1_SAVINGS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Podejrzewam że przeplącamy za usługi transportowe. Dostawca mówi że ma najlepszą cenę na rynku. Jak sprawdzić czy to prawda?",
        expectedKeywords: ["should-cost", "benchmark", "analiz", "koszt", "rynk", "dane", "faktach"],
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Transport to kategoria za 8 mln PLN. Umowa jest od 4 lat bez renegocjacji.",
        expectedKeywords: ["should-cost", "potencjał", "renegocjacj", "dane", "rynk", "oszczędności"],
        expectsEscalation: true,
      },
    ],
    expectedIntent: "I1_SAVINGS",
    tags: ["should-cost", "transport", "overpaying"],
  },
  {
    id: "A-012",
    category: "A-procurement-operations",
    title: "Category strategy request",
    description: "Company wants to build its first category strategy for packaging — 15 mln PLN spend.",
    locale: "pl",
    pageSlug: "services/strategia-kategorii",
    pageContext: makePageContext("services/strategia-kategorii", "I5_SOURCING"),
    sessionState: makeSessionState({ detectedIntent: "I5_SOURCING", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Chcemy zbudować pierwszą strategię kategorii dla opakowań. 15 mln PLN rocznie, 23 dostawcó, duże rozproszenie. Jak to ugryźć?",
        expectedKeywords: ["strategia", "segmentacj", "spend", "benchmark", "potencjał", "dostawcó", "konsolidacj"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["category-strategy", "packaging", "first-strategy"],
  },
  {
    id: "A-013",
    category: "A-procurement-operations",
    title: "Multiple simultaneous supplier issues",
    description: "Quality issues, price increases, and delivery delays from 3 different key suppliers at once.",
    locale: "pl",
    pageSlug: "services/zarzadzanie-ryzykiem",
    pageContext: makePageContext("services/zarzadzanie-ryzykiem", "I3_SUPPLIER_RISK"),
    sessionState: makeSessionState({ detectedIntent: "I3_SUPPLIER_RISK", urgency: "U1", maturity: "reactive" }),
    turns: [
      {
        user: "Jednocześnie: Dostawca A podwyższa ceny o 12%, Dostawca B ma problemy jakościowe, Dostawca C opóźnia dostawy o 6 tygodni. Trzy kluczowe kategorie. Wszystko pilne.",
        expectedKeywords: ["priorytet", "ryzyko", "kategorii", "plan", "działania", "analiz"],
        forbiddenPhrases: ["to skomplikowana sytuacja", "rozumiem że to trudne"],
        expectsDiagnosticQuestion: true,
      },
    ],
    expectedUrgency: "U1",
    tags: ["multi-issue", "risk", "U1", "complex"],
  },
  {
    id: "A-014",
    category: "A-procurement-operations",
    title: "Procurement digitalization confusion",
    description: "Company considering eSourcing, spend analytics, and P2P system. Doesn't know where to start.",
    locale: "pl",
    pageSlug: "services/digitalizacja",
    pageContext: makePageContext("services/digitalizacja", "I4_DIGITALIZATION"),
    sessionState: makeSessionState({ detectedIntent: "I4_DIGITALIZATION", urgency: "U3", maturity: "reactive" }),
    turns: [
      {
        user: "Mamy oferty od 3 dostawców systemów: jeden oferuje spend analytics, drugi eSourcing, trzeci cały P2P. Nie wiem od czego zacząć. Mamy 500k PLN budżet.",
        expectedKeywords: ["priorytet", "dojrzałości", "potrzeb", "maturity", "diagnoz", "zacząć"],
        expectsDiagnosticQuestion: true,
      },
    ],
    expectedIntent: "I4_DIGITALIZATION",
    tags: ["digitalization", "system-selection", "budget"],
  },
  {
    id: "A-015",
    category: "A-procurement-operations",
    title: "Cost reduction target from board",
    description: "Board set 7% cost reduction target for next fiscal year. Procurement has no idea how to deliver.",
    locale: "pl",
    pageSlug: "services/analiza-spot",
    pageContext: makePageContext("services/analiza-spot", "I1_SAVINGS"),
    sessionState: makeSessionState({ detectedIntent: "I1_SAVINGS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Zarząd wyznaczył cel 7% redukcji kosztów w przyszłym roku fiskalnym. Zakupy dostały mandat. Spend to 120 mln PLN. Od czego zacząć i czy to realne?",
        expectedKeywords: ["potencjał", "kategorii", "analiz", "spend", "priorytet", "osiągaln"],
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Nie mamy danych o strukturze spend. Nie wiem co kupujemy i gdzie jest potencjał.",
        expectedKeywords: ["spend cube", "analiz", "widoczność", "SPOT", "priorytet"],
        expectsEscalation: true,
      },
    ],
    tags: ["board-target", "cost-reduction", "7%", "spend-visibility"],
  },
  {
    id: "A-016",
    category: "A-procurement-operations",
    title: "Supplier quality issues + cost pressure simultaneously",
    description: "Key supplier has quality problems AND is pushing for price increase. Buyer is paralyzed.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U1", maturity: "developing" }),
    turns: [
      {
        user: "Nasz główny dostawca ma ostatnio problemy jakościowe — 3 reklamacje w tym kwartale — i jednocześnie chce podwyżki o 9%. Jak zarządzać tym dostawcą?",
        expectedKeywords: ["jakość", "dźwignia", "negocjacj", "reklamacj", "kontrakt", "warunki", "leverage"],
        forbiddenPhrases: ["to trudna sytuacja", "rozumiem"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["quality-issues", "price-increase", "leverage", "dual-problem"],
  },
  {
    id: "A-017",
    category: "A-procurement-operations",
    title: "Long-tail supplier management",
    description: "Company has 4,500 suppliers for €800k spend in long tail. Massive administration.",
    locale: "en",
    pageSlug: "services/spend-analytics",
    pageContext: makePageContext("services/spend-analytics", "I2_FORECASTING"),
    sessionState: makeSessionState({ detectedIntent: "I2_FORECASTING", urgency: "U3", maturity: "reactive" }),
    turns: [
      {
        user: "We have 4,500 active suppliers for €800k of long tail spend. It's an administrative nightmare. How do we fix this?",
        expectedKeywords: ["consolidat", "Pareto", "spend analytic", "segmentat", "tail", "rationaliz"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["long-tail", "supplier-rationalization", "EN"],
  },
  {
    id: "A-018",
    category: "A-procurement-operations",
    title: "New CPO — strategic sourcing maturity assessment",
    description: "New CPO wants objective maturity assessment before making investments.",
    locale: "en",
    pageSlug: "services/transformacja",
    pageContext: makePageContext("services/transformacja", "I5_SOURCING"),
    sessionState: makeSessionState({ detectedIntent: "I5_SOURCING", urgency: "U3", maturity: "developing" }),
    turns: [
      {
        user: "I've joined as CPO 6 weeks ago. Before I propose any investments, I need an objective assessment of where our procurement maturity stands. How do you approach this?",
        expectedKeywords: ["maturity", "assessment", "diagnos", "benchmark", "model", "spend", "categor"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["CPO", "maturity-assessment", "EN", "strategic"],
  },
  {
    id: "A-019",
    category: "A-procurement-operations",
    title: "Procurement operating model redesign",
    description: "Company merging two procurement teams across countries. Need new operating model.",
    locale: "en",
    pageSlug: "services/transformacja",
    pageContext: makePageContext("services/transformacja", "I5_SOURCING"),
    sessionState: makeSessionState({ detectedIntent: "I5_SOURCING", urgency: "U2", maturity: "strategic" }),
    turns: [
      {
        user: "We're merging Polish and Czech procurement teams after an acquisition. Different systems, different suppliers, different cultures. We need a new operating model. Where do we start?",
        expectedKeywords: ["operating model", "integrat", "categor", "process", "govern", "spend"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["operating-model", "M&A", "integration", "EN"],
  },
  {
    id: "A-020",
    category: "A-procurement-operations",
    title: "Procurement KPI system — no metrics",
    description: "Procurement team has zero KPIs. Board wants accountability. CPO needs framework fast.",
    locale: "pl",
    pageSlug: "services/spend-analytics",
    pageContext: makePageContext("services/spend-analytics", "I2_FORECASTING"),
    sessionState: makeSessionState({ detectedIntent: "I2_FORECASTING", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Zarząd chce mierzyć efektywność zakupów, ale nie mamy żadnych KPI. Nie wiem od czego zacząć i co w ogóle mierzyć.",
        expectedKeywords: ["KPI", "oszczędności", "spend", "dostawcó", "jakość", "lead time", "metryki"],
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Priorytet to pokazanie wartości zakupów na poziomie zarządu. Chcemy dashboard, który przekona CFO.",
        expectedKeywords: ["dashboard", "CFO", "marż", "oszczędności", "KPI", "wartość", "biznes"],
        expectsEscalation: true,
      },
    ],
    tags: ["KPIs", "dashboard", "CFO", "accountability"],
  },
];
