// ─────────────────────────────────────────────────────────
// ETAP 7.5 — Scenarios: B. NEGOTIATION INTELLIGENCE (20)
// ─────────────────────────────────────────────────────────

import type { AdvisoryScenario } from "../types/index";
import { makeSessionState, makePageContext } from "../types/index";

export const B_NEGOTIATION_INTELLIGENCE: AdvisoryScenario[] = [
  {
    id: "B-001",
    category: "B-negotiation-intelligence",
    title: "Supplier bluff — 'best price already'",
    description: "Supplier claims current price is already the best possible, no room for reduction.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing", intentConfidence: 0.85 }),
    turns: [
      {
        user: "Dostawca mówi że mamy już najlepszą cenę na rynku i nie ma żadnej przestrzeni na obniżenie. Jak to zweryfikować i jak zareagować?",
        expectedKeywords: ["benchmark", "rynk", "dane", "should-cost", "weryfikacj", "alternatyw", "blef"],
        forbiddenPhrases: ["to możliwe że mają rację", "rynek jest teraz drogi"],
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Nie mamy benchmarków dla tej kategorii. Dostawca to wie.",
        expectedKeywords: ["benchmarking", "danych", "should-cost", "analiz", "rynk", "dźwigni"],
        note: "Advisor must not accept supplier claim at face value. Must recommend data gathering.",
      },
    ],
    expectedIntent: "I8_NEGOTIATIONS",
    tags: ["supplier-bluff", "best-price-claim", "benchmarking"],
  },
  {
    id: "B-002",
    category: "B-negotiation-intelligence",
    title: "Fake inflation data — supplier manipulation",
    description: "Supplier presents selective inflation data to justify 18% increase. Data looks cherry-picked.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U1", maturity: "developing" }),
    turns: [
      {
        user: "Dostawca przysłał dane inflacyjne: PPI +22%, energia +35%, praca +18%. Na tej podstawie żąda 18% podwyżki. Jak sprawdzić czy te dane są prawdziwe i jak kontrować?",
        expectedKeywords: ["indeks", "GUS", "PPI", "weryfikacj", "koszyk", "udział", "struktura kosztów", "should-cost"],
        forbiddenPhrases: ["to możliwe że inflacja jest", "dane wyglądają"],
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Mamy dostęp do danych GUS. Jak zbudować kontrargument?",
        expectedKeywords: ["struktura", "udział", "energia", "surowce", "praca", "weryfikacj", "model"],
        note: "Advisor must challenge index manipulation — key ETAP 7 tactic.",
      },
    ],
    tags: ["index-manipulation", "fake-inflation", "PPI", "counter-data"],
  },
  {
    id: "B-003",
    category: "B-negotiation-intelligence",
    title: "Anchoring — supplier opens extremely high",
    description: "Supplier opens negotiation at 145% of market rate. Classic anchoring tactic.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Dostawca otworzył negocjacje ceną 45% wyższą niż nasz budżet i wyżej niż jakikolwiek benchmark który mam. Mówi że to 'fair market price'. Co teraz?",
        expectedKeywords: ["anchoring", "zakotwiczen", "kontrujemy", "własną kotwicę", "odrzucić", "dane", "benchmark"],
        forbiddenPhrases: ["to może być ich cena", "warto spróbować wynegocjować z tej kwoty"],
        note: "Must not accept the anchor. Must advise on counter-anchoring strategy.",
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["anchoring", "counter-anchoring", "price-manipulation"],
  },
  {
    id: "B-004",
    category: "B-negotiation-intelligence",
    title: "Concession trap — volume guarantee demanded upfront",
    description: "Supplier demands volume commitment before discussing price. Classic concession trap.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "reactive" }),
    turns: [
      {
        user: "Zanim dostawca poda nam cenę, chce żebyśmy zobowiązali się do minimalnego wolumenu przez 3 lata. Czy powinienem się zgodzić żeby w ogóle zacząć negocjacje?",
        expectedKeywords: ["ustępstw", "bez wzajemności", "pułapka", "kolejność", "warunki", "kontrakt", "nie"],
        forbiddenPhrases: ["może warto spróbować", "to normalna praktyka"],
        note: "Must clearly flag this as a concession trap. Must not advise accepting the precondition.",
      },
    ],
    tags: ["concession-trap", "volume-commitment", "precondition"],
  },
  {
    id: "B-005",
    category: "B-negotiation-intelligence",
    title: "Artificial urgency — offer expires Friday",
    description: "Supplier claims offer is valid only until end of week. Creates false scarcity and urgency.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "reactive" }),
    turns: [
      {
        user: "Dostawca mówi że oferta jest ważna tylko do piątku i potem cena wzrośnie o kolejne 8%. To jutro. Czy mam się zgadzać pod presją czasu?",
        expectedKeywords: ["presja czasu", "sztuczna", "pilność", "nie rezygnuj", "deadline", "test blefa"],
        forbiddenPhrases: ["może rzeczywiście jest ograniczona oferta", "lepiej się zdecydować"],
        note: "Must clearly identify artificial urgency tactic. Must NOT recommend caving.",
      },
    ],
    tags: ["artificial-urgency", "deadline-pressure", "time-pressure"],
  },
  {
    id: "B-006",
    category: "B-negotiation-intelligence",
    title: "Take-it-or-leave-it ultimatum",
    description: "Supplier presents final offer, says negotiation is over. No room for further discussion.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Dostawca powiedział 'to jest finalna oferta, take it or leave it'. Nie chce rozmawiać o cenie. Jak zareagować?",
        expectedKeywords: ["ultimatum", "strategia", "inne osie", "zmień", "poczekaj", "BATNA", "nie rezygnuj z negocjacji"],
        forbiddenPhrases: ["jeśli nie ma przestrzeni", "może rzeczywiście jest finalne"],
        note: "Must not accept ultimatum at face value. Must offer multi-axis strategy.",
      },
    ],
    tags: ["take-it-or-leave-it", "ultimatum", "negotiation-tactics"],
  },
  {
    id: "B-007",
    category: "B-negotiation-intelligence",
    title: "Index manipulation — CPI/PPI misuse",
    description: "Supplier uses wrong price index to justify increase. Deliberately misapplying index.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U1", maturity: "developing" }),
    turns: [
      {
        user: "Dostawca usług IT podnosi ceny o 14% powołując się na PPI dla przemysłu. Ale oni świadczą usługi, nie produkują. Czy to poprawny indeks?",
        expectedKeywords: ["indeks", "IT", "usługi", "CPI", "praca", "struktura kosztów", "błędny indeks", "weryfikacj"],
        note: "Must detect index misapplication. This is a critical negotiation intelligence test.",
      },
    ],
    tags: ["index-manipulation", "wrong-index", "IT-services"],
  },
  {
    id: "B-008",
    category: "B-negotiation-intelligence",
    title: "Emotional supplier pressure — relationship leverage",
    description: "Supplier invokes 10-year relationship to avoid price challenge. 'After all we've done for you...'",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "reactive" }),
    turns: [
      {
        user: "Dostawca mówi że jesteśmy 10 lat razem i teraz kwestionujemy jego ceny — to jest brak szacunku dla relacji. Czuję się winny ale ceny są za wysokie.",
        expectedKeywords: ["emocjonalna", "relacja", "biznesow", "oddziel", "oczekiwania", "dane", "fakty"],
        forbiddenPhrases: ["relacja jest ważna więc może", "rozumiem trudność tej rozmowy"],
        note: "Must help buyer disentangle emotional from commercial. Classic relationship leverage tactic.",
      },
    ],
    tags: ["emotional-pressure", "relationship-leverage", "manipulation"],
  },
  {
    id: "B-009",
    category: "B-negotiation-intelligence",
    title: "Fake scarcity — last available capacity slot",
    description: "Supplier claims they're almost fully booked and buyer must commit now or lose capacity.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "reactive" }),
    turns: [
      {
        user: "Dostawca mówi że ma tylko jedno wolne miejsce w przyszłym kwartale i musimy się zobowiązać teraz. Czy to możliwe że faktycznie nie ma miejsca?",
        expectedKeywords: ["fałszywa niedobór", "test", "zweryfikuj", "czy naprawdę", "alternatyw", "blef"],
        forbiddenPhrases: ["może rzeczywiście", "lepiej się zabezpieczyć"],
        note: "Advisor must challenge fake scarcity. Classic ETAP 7 false_scarcity tactic.",
      },
    ],
    tags: ["fake-scarcity", "capacity-pressure", "false-urgency"],
  },
  {
    id: "B-010",
    category: "B-negotiation-intelligence",
    title: "Supplier tactical escalation to MD level",
    description: "Supplier's MD calls buyer's CEO to discuss 'partnership'. Bypassing procurement.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U1", maturity: "developing" }),
    turns: [
      {
        user: "Dyrektor dostawcy zadzwonił do naszego CEO z pominięciem mnie. CEO mówi żeby 'być elastycznym'. Straciłem pozycję negocjacyjną?",
        expectedKeywords: ["eskalacja", "CEO", "wewnętrzn", "pozycja", "zakupy", "aliansu", "brief", "ponownie"],
        expectsDiagnosticQuestion: true,
        note: "Advisor must help rebuild internal alignment. Classic supplier escalation tactic.",
      },
    ],
    tags: ["supplier-escalation", "MD-escalation", "internal-alignment"],
  },
  {
    id: "B-011",
    category: "B-negotiation-intelligence",
    title: "Multi-supplier negotiation orchestration",
    description: "Buyer has 3 qualified suppliers and wants to run competitive negotiation across all three.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Mam 3 kwalifikowanych dostawców i chcę przeprowadzić negocjacje ze wszystkimi jednocześnie. Jak to zorganizować i jak nie zdradzić kart żadnemu z nich?",
        expectedKeywords: ["równolegle", "przetarg", "eAukcja", "sekwencja", "informacj", "BATNA", "oferty"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["multi-supplier", "competitive-negotiation", "auction"],
  },
  {
    id: "B-012",
    category: "B-negotiation-intelligence",
    title: "Negotiation preparation — what exactly to prepare",
    description: "Buyer about to enter first structured negotiation. Needs concrete preparation framework.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "reactive" }),
    turns: [
      {
        user: "Za 2 tygodnie mam pierwsze duże negocjacje kontraktu. Co dokładnie powinienem przygotować? Jakie dokumenty, dane, argumenty?",
        expectedKeywords: ["benchmark", "BATNA", "cele", "zakres", "dane", "ustępstw", "strategia"],
        note: "Should give concrete preparation framework, not generic negotiation advice.",
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["negotiation-prep", "first-negotiation", "framework"],
  },
  {
    id: "B-013",
    category: "B-negotiation-intelligence",
    title: "Countering price increase narrative",
    description: "Supplier presents 10-slide deck justifying price increase. How to counter systematically.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U1", maturity: "developing" }),
    turns: [
      {
        user: "Dostawca zrobił 10-slajdową prezentację uzasadniającą podwyżkę. Slajdy wyglądają profesjonalnie. Jak ją rozebrać analitycznie?",
        expectedKeywords: ["struktura kosztów", "udział", "indeks", "surowce", "weryfikacj", "dane GUS", "counter"],
        note: "Advisor must give concrete analytical deconstruction approach.",
      },
    ],
    tags: ["counter-narrative", "price-presentation", "analytical-deconstruction"],
  },
  {
    id: "B-014",
    category: "B-negotiation-intelligence",
    title: "Electronic auction eligibility",
    description: "Buyer asks if their category is suitable for eAuction. Needs clear diagnostic.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Czy moja kategoria nadaje się na eAukcję? Mamy usługi sprzątania, 6 potencjalnych dostawców, kontrakt 1.2 mln PLN rocznie.",
        expectedKeywords: ["eAukcja", "warunki", "standaryzacja", "dostawcó", "liczba", "porównywaln", "kryteria"],
        expectsDiagnosticQuestion: true,
        note: "Advisor must assess auction eligibility criteria — not just say 'yes' or 'no'.",
      },
    ],
    tags: ["eauction", "auction-eligibility", "cleaning-services"],
  },
  {
    id: "B-015",
    category: "B-negotiation-intelligence",
    title: "BATNA building — no alternatives",
    description: "Buyer has no alternatives to current supplier. Needs BATNA development strategy.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "reactive" }),
    turns: [
      {
        user: "Wiem że muszę mieć alternatywę ale nie mam. Jedyny dostawca który spełnia nasze wymagania. Jak budować BATNA w takiej sytuacji?",
        expectedKeywords: ["BATNA", "alternatyw", "kwalifikacj", "specyfikacj", "czas", "kredybilność", "sygnał"],
        note: "Advisor must understand BATNA building process — not just say 'find alternatives'.",
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["BATNA", "no-alternatives", "single-source"],
  },
  {
    id: "B-016",
    category: "B-negotiation-intelligence",
    title: "Concession strategy design",
    description: "Buyer needs to make some concessions but wants to control the process.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Wiem że muszę coś oddać w tych negocjacjach. Jak planować ustępstwa żeby nie stracić za dużo i żeby dostawca czuł że coś dostał?",
        expectedKeywords: ["ustępstwo", "sekwencja", "wymiana", "wzajemność", "wartość", "tanie dla mnie", "drogie"],
        note: "Must give concrete concession strategy — not generic negotiation advice.",
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["concession-strategy", "controlled-concession"],
  },
  {
    id: "B-017",
    category: "B-negotiation-intelligence",
    title: "Negotiation workshop request",
    description: "CPO wants to run negotiation workshop for team of 8 buyers. Needs program design.",
    locale: "pl",
    pageSlug: "services/szkolenia",
    pageContext: makePageContext("services/szkolenia", "I6_EDUCATION"),
    sessionState: makeSessionState({ detectedIntent: "I6_EDUCATION", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Chcę przeszkolić moich 8 kupców z negocjacji. Mają różne poziomy. Jak zbudować program szkoleniowy który da realne umiejętności a nie tylko teorię?",
        expectedKeywords: ["warsztat", "praktyk", "symulacj", "Harvard", "metodologi", "kategori", "real"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["negotiation-training", "workshop", "team-capability"],
  },
  {
    id: "B-018",
    category: "B-negotiation-intelligence",
    title: "Supplier data manipulation challenge",
    description: "Supplier presents selectively chosen benchmarks that support their position.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U1", maturity: "developing" }),
    turns: [
      {
        user: "Dostawca przyniósł badanie branżowe które pokazuje że nasza cena jest 12% poniżej rynku. Badanie jest od nieznanej organizacji. Czy to wiarygodne?",
        expectedKeywords: ["źródło", "niezależn", "weryfikacj", "metodologi", "próba", "counter-benchmark"],
        note: "Must challenge data source credibility. Classic selective_benchmarking tactic.",
      },
    ],
    tags: ["selective-benchmarking", "data-manipulation", "credibility"],
  },
  {
    id: "B-019",
    category: "B-negotiation-intelligence",
    title: "Multi-axis negotiation design",
    description: "Buyer wants to negotiate more than just price — payment terms, quality, volume flexibility.",
    locale: "en",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "I want to negotiate beyond just price. Payment terms, quality guarantees, volume flexibility, delivery. How do I design a multi-axis negotiation?",
        expectedKeywords: ["multi-axis", "trade", "payment terms", "value", "levers", "scope", "BATNA"],
        expectsDiagnosticQuestion: true,
        note: "Must provide concrete multi-axis negotiation framework.",
      },
    ],
    tags: ["multi-axis", "negotiation-design", "EN"],
  },
  {
    id: "B-020",
    category: "B-negotiation-intelligence",
    title: "Post-negotiation review — outcome was poor",
    description: "Buyer accepted poor deal under pressure. Wants to understand what went wrong.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U3", maturity: "reactive" }),
    turns: [
      {
        user: "Właśnie skończyłem negocjacje i mam wrażenie że dałem za dużo. Dostawca dostał 8% podwyżkę choć miałem limit 4%. Co poszło nie tak?",
        expectedKeywords: ["analiz", "ustępstw", "presja", "BATNA", "przygotowanie", "diagnoz", "lekcj"],
        expectsDiagnosticQuestion: true,
        note: "Must help analyze what went wrong. Focus on structural issues not blame.",
      },
    ],
    tags: ["post-negotiation", "poor-outcome", "lessons-learned"],
  },
];
