// ─────────────────────────────────────────────────────────
// ETAP 7.5 — Scenarios: C. EXECUTIVE CONVERSATIONS (20)
// ─────────────────────────────────────────────────────────

import type { AdvisoryScenario } from "../types/index";
import { makeSessionState, makePageContext } from "../types/index";

export const C_EXECUTIVE_CONVERSATIONS: AdvisoryScenario[] = [
  {
    id: "C-001",
    category: "C-executive-conversations",
    title: "CFO: ROI question — direct challenge",
    description: "CFO directly challenges expected ROI of engaging Profitia. Short, sharp question.",
    locale: "pl",
    pageSlug: "services/analiza-spot",
    pageContext: makePageContext("services/analiza-spot", "I1_SAVINGS"),
    sessionState: makeSessionState({ detectedIntent: "I1_SAVINGS", urgency: "U2", maturity: "strategic", intentConfidence: 0.8, buyingStage: "decision" }),
    turns: [
      {
        user: "Jaki ROI powinienem oczekiwać z zaangażowania Profitia? Potrzebuję liczb.",
        expectedKeywords: ["oszczędności", "spend", "kategorii", "potencjał", "zależy", "zakres", "benchmark"],
        forbiddenPhrases: ["świetne pytanie", "to zależy od wielu czynników", "trudno powiedzieć bez"],
        expectsDiagnosticQuestion: true,
        note: "Must not dodge. Must give structured answer with real ranges AND ask qualifying question.",
      },
      {
        user: "Mamy 80 mln PLN spend zakupowy. Ile możemy zaoszczędzić realnie?",
        expectedKeywords: ["procent", "kategorii", "potencjał", "oszczędności", "zależy", "SPOT", "diagnosis"],
        expectsEscalation: true,
      },
    ],
    expectedIntent: "I1_SAVINGS",
    expectedEscalation: true,
    tags: ["CFO", "ROI", "executive", "direct-challenge"],
  },
  {
    id: "C-002",
    category: "C-executive-conversations",
    title: "CFO: EBIT impact",
    description: "CFO wants to understand procurement's contribution to EBIT improvement.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "I1_SAVINGS"),
    sessionState: makeSessionState({ detectedIntent: "I1_SAVINGS", urgency: "U2", maturity: "strategic" }),
    turns: [
      {
        user: "Jak poprawa zakupów przełoży się na EBIT? Interesuje mnie tylko finansowy wynik.",
        expectedKeywords: ["EBIT", "marż", "oszczędności", "koszt sprzedanych", "bezpośredni", "wpływ", "P&L"],
        forbiddenPhrases: ["zakupy mają wiele korzyści", "trudno jednoznacznie"],
        expectsDiagnosticQuestion: true,
      },
    ],
    expectedIntent: "I1_SAVINGS",
    tags: ["CFO", "EBIT", "financial-impact", "executive"],
  },
  {
    id: "C-003",
    category: "C-executive-conversations",
    title: "CEO: Board presentation on procurement savings",
    description: "CEO preparing board presentation and needs procurement savings narrative.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "I1_SAVINGS"),
    sessionState: makeSessionState({ detectedIntent: "I1_SAVINGS", urgency: "U2", maturity: "strategic", buyingStage: "consideration" }),
    turns: [
      {
        user: "Za 3 tygodnie mam prezentację dla rady nadzorczej. Chcę pokazać potencjał optymalizacji zakupów. Co i jak pokazać?",
        expectedKeywords: ["spend", "kategorii", "potencjał", "benchmark", "oszczędności", "road map", "narracja"],
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Nasz spend to 150 mln PLN. 60% to TOP 5 kategorii. Nie mamy danych o potencjale.",
        expectedKeywords: ["SPOT", "analiz", "szybk", "kategorii", "dane", "potencjał", "3 tygodnie"],
        expectsEscalation: true,
      },
    ],
    tags: ["CEO", "board-presentation", "savings-narrative"],
  },
  {
    id: "C-004",
    category: "C-executive-conversations",
    title: "CPO: Team can't negotiate effectively",
    description: "CPO admits team loses every negotiation. Looking for systemic fix.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Mój zespół przegrywa każde negocjacje. Dostawcy nas wyczuli. Potrzebuję systemowego rozwiązania, nie jednorazowego szkolenia.",
        expectedKeywords: ["systemowr", "danymi", "warsztat", "przygotowanie", "benchmark", "kategori", "couch"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["CPO", "team-capability", "negotiation-system"],
  },
  {
    id: "C-005",
    category: "C-executive-conversations",
    title: "Board expectations — ambitious cost reduction",
    description: "Board set 12% cost reduction target. CPO considers it unrealistic.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "I1_SAVINGS"),
    sessionState: makeSessionState({ detectedIntent: "I1_SAVINGS", urgency: "U1", maturity: "strategic" }),
    turns: [
      {
        user: "Zarząd oczekuje 12% redukcji kosztów zakupowych. Uważam że to nierealne w 12 miesięcy. Jak to ocenić i co powiedzieć zarządowi?",
        expectedKeywords: ["potencjał", "realiz", "kategorii", "baseline", "zakres", "spend", "plan"],
        expectsDiagnosticQuestion: true,
        note: "Must help executive have honest conversation with board — not just validate expectations.",
      },
    ],
    tags: ["board-expectations", "realistic-targets", "executive-advisory"],
  },
  {
    id: "C-006",
    category: "C-executive-conversations",
    title: "Procurement transformation business case",
    description: "CPO needs to build internal business case for procurement transformation investment.",
    locale: "en",
    pageSlug: "services/transformacja",
    pageContext: makePageContext("services/transformacja", "I5_SOURCING"),
    sessionState: makeSessionState({ detectedIntent: "I5_SOURCING", urgency: "U2", maturity: "strategic" }),
    turns: [
      {
        user: "I need to build a business case for a €300k procurement transformation investment. CFO needs hard numbers. How do I structure it?",
        expectedKeywords: ["ROI", "savings", "baseline", "potential", "categor", "invest", "payback"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["business-case", "transformation-investment", "EN", "CFO"],
  },
  {
    id: "C-007",
    category: "C-executive-conversations",
    title: "Strategic sourcing maturity — where are we?",
    description: "CEO asks for honest assessment of procurement maturity vs industry peers.",
    locale: "pl",
    pageSlug: "services/transformacja",
    pageContext: makePageContext("services/transformacja", "I5_SOURCING"),
    sessionState: makeSessionState({ detectedIntent: "I5_SOURCING", urgency: "U3", maturity: "strategic" }),
    turns: [
      {
        user: "Gdzie jesteśmy jako organizacja zakupowa w porównaniu do firm podobnej wielkości? Chcę szczerą odpowiedź.",
        expectedKeywords: ["dojrzałość", "benchmark", "reaktywn", "strategiczn", "poziom", "model", "ocena"],
        expectsDiagnosticQuestion: true,
        note: "Must give structured answer with maturity model context. Not just 'it depends'.",
      },
    ],
    tags: ["maturity-assessment", "CEO", "benchmark-vs-peers"],
  },
  {
    id: "C-008",
    category: "C-executive-conversations",
    title: "Digital procurement strategy",
    description: "CTO and CPO together deciding on procurement digitalization roadmap.",
    locale: "pl",
    pageSlug: "services/digitalizacja",
    pageContext: makePageContext("services/digitalizacja", "I4_DIGITALIZATION"),
    sessionState: makeSessionState({ detectedIntent: "I4_DIGITALIZATION", urgency: "U3", maturity: "strategic" }),
    turns: [
      {
        user: "Mamy budżet 800k PLN na digitalizację zakupów. CTO rekomenduje jeden duży system, ja chcę modularne podejście. Jak to rozstrzygnąć?",
        expectedKeywords: ["priorytet", "modularnie", "zakres", "dojrzałość", "potrzeb", "strategia", "ryzyko"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["digitalization-strategy", "CTO-CPO", "build-vs-buy"],
  },
  {
    id: "C-009",
    category: "C-executive-conversations",
    title: "MD: Suppliers increase prices every year",
    description: "Managing Director frustrated with annual supplier increases. Wants systemic response.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "reactive" }),
    turns: [
      {
        user: "Każdy rok to samo — dostawcy podnoszą ceny i my płacimy więcej. Moi kupcy nie potrafią tego zatrzymać. Co jest nie tak?",
        expectedKeywords: ["systemowr", "dane", "benchmark", "kategori", "negocjacj", "przygotowanie", "dźwigni"],
        forbiddenPhrases: ["to trudny rynek", "dostawcy mają rację"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["MD", "systemic-problem", "annual-increases"],
  },
  {
    id: "C-010",
    category: "C-executive-conversations",
    title: "CFO: Cash flow from payment terms optimization",
    description: "CFO interested in improving cash flow through procurement payment terms.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "strategic" }),
    turns: [
      {
        user: "Ile możemy poprawić cash flow przez renegocjację warunków płatności z dostawcami? Interesuje mnie DPO.",
        expectedKeywords: ["DPO", "warunki płatności", "cash flow", "dostawcó", "ryzyko", "negocjacj", "kategorii"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["CFO", "cash-flow", "DPO", "payment-terms"],
  },
  {
    id: "C-011",
    category: "C-executive-conversations",
    title: "CEO: Supplier risk after geopolitical disruption",
    description: "CEO worried about supply chain resilience after recent geopolitical events.",
    locale: "en",
    pageSlug: "services/zarzadzanie-ryzykiem",
    pageContext: makePageContext("services/zarzadzanie-ryzykiem", "I3_SUPPLIER_RISK"),
    sessionState: makeSessionState({ detectedIntent: "I3_SUPPLIER_RISK", urgency: "U1", maturity: "strategic" }),
    turns: [
      {
        user: "Our board is asking about supply chain resilience after the latest disruptions. What should I be looking at?",
        expectedKeywords: ["risk", "concentration", "single-source", "dual-source", "resilience", "categor", "critical"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["CEO", "supply-chain-risk", "geopolitical", "EN"],
  },
  {
    id: "C-012",
    category: "C-executive-conversations",
    title: "CPO: Category management implementation",
    description: "CPO wants to implement category management for the first time in 3 years.",
    locale: "pl",
    pageSlug: "services/strategia-kategorii",
    pageContext: makePageContext("services/strategia-kategorii", "I5_SOURCING"),
    sessionState: makeSessionState({ detectedIntent: "I5_SOURCING", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Chcę wdrożyć zarządzanie kategoriami. Mam 12 kupców i 80 kategorii. Od czego zacząć i jak priorytetyzować?",
        expectedKeywords: ["priorytet", "spend", "kategorii", "model", "strategiczn", "Pareto", "pilot"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["CPO", "category-management", "implementation"],
  },
  {
    id: "C-013",
    category: "C-executive-conversations",
    title: "CFO: Should-cost ROI question",
    description: "CFO skeptical about should-cost investment — wants clear financial logic.",
    locale: "pl",
    pageSlug: "services/should-cost",
    pageContext: makePageContext("services/should-cost", "I1_SAVINGS"),
    sessionState: makeSessionState({ detectedIntent: "I1_SAVINGS", urgency: "U2", maturity: "strategic" }),
    turns: [
      {
        user: "Mój doradca mówi że should-cost analysis to podstawa. Ile to kosztuje i jaki jest zwrot? Nie lubię płacić za analizy.",
        expectedKeywords: ["should-cost", "inwestycj", "zwrot", "negocjacj", "oszczędności", "potencjał", "warto"],
        forbiddenPhrases: ["rozumiem sceptycyzm", "to zależy", "warto rozważyć"],
        expectsDiagnosticQuestion: true,
        note: "CFO is direct and skeptical. Advisor must respond with business logic, not consultancy fluff.",
      },
    ],
    tags: ["CFO", "should-cost", "ROI-skepticism"],
  },
  {
    id: "C-014",
    category: "C-executive-conversations",
    title: "VP Supply Chain: Procurement collaboration",
    description: "VP Supply Chain wants to improve procurement-supply chain alignment.",
    locale: "en",
    pageSlug: "/",
    pageContext: makePageContext("/", "I5_SOURCING"),
    sessionState: makeSessionState({ detectedIntent: "I5_SOURCING", urgency: "U3", maturity: "strategic" }),
    turns: [
      {
        user: "Procurement and supply chain work in silos. We're losing efficiency. How do we build a joined-up approach?",
        expectedKeywords: ["alignment", "process", "KPI", "shared", "categor", "demand", "operating model"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["VP-supply-chain", "cross-functional", "alignment", "EN"],
  },
  {
    id: "C-015",
    category: "C-executive-conversations",
    title: "MD: How to know if my team is competent?",
    description: "MD frustrated — can't objectively assess if procurement team is performing well.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "I5_SOURCING"),
    sessionState: makeSessionState({ detectedIntent: "I5_SOURCING", urgency: "U2", maturity: "reactive" }),
    turns: [
      {
        user: "Mój dział zakupów mówi że robi dobrą robotę. Ale nie wiem jak to ocenić. Jak sprawdzić czy naprawdę jest kompetentny?",
        expectedKeywords: ["benchmark", "KPI", "ocena", "dojrzałość", "rynk", "spend", "wyniki", "audit"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["MD", "team-competence", "assessment"],
  },
  {
    id: "C-016",
    category: "C-executive-conversations",
    title: "CFO: Spend visibility vs savings — what first?",
    description: "CFO asks whether to invest in visibility first or go straight to savings initiatives.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "I1_SAVINGS"),
    sessionState: makeSessionState({ detectedIntent: "I1_SAVINGS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Mamy dwa zadania: zbudować widoczność spend lub od razu szukać oszczędności. Na co przeznaczyć pierwsze 300k PLN? Mamy 12 miesięcy.",
        expectedKeywords: ["widoczność", "priorytet", "oszczędności", "kategorii", "quick wins", "plan", "sekwencja"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["CFO", "visibility-vs-savings", "investment-prioritization"],
  },
  {
    id: "C-017",
    category: "C-executive-conversations",
    title: "CEO: Make vs buy decision",
    description: "CEO considering in-sourcing key category currently outsourced.",
    locale: "en",
    pageSlug: "/",
    pageContext: makePageContext("/", "I5_SOURCING"),
    sessionState: makeSessionState({ detectedIntent: "I5_SOURCING", urgency: "U2", maturity: "strategic" }),
    turns: [
      {
        user: "We're considering bringing warehousing in-house. Currently outsourced at €1.2M/year. Should we?",
        expectedKeywords: ["make vs buy", "total cost", "capex", "opex", "risk", "core competenc", "analyz"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["CEO", "make-vs-buy", "insourcing", "EN"],
  },
  {
    id: "C-018",
    category: "C-executive-conversations",
    title: "CPO: Operating model redesign",
    description: "CPO wants to move from decentralized to centralized/hybrid procurement model.",
    locale: "pl",
    pageSlug: "services/transformacja",
    pageContext: makePageContext("services/transformacja", "I5_SOURCING"),
    sessionState: makeSessionState({ detectedIntent: "I5_SOURCING", urgency: "U3", maturity: "strategic" }),
    turns: [
      {
        user: "Chcę przejść z modelu zdecentralizowanego na hybrydowy. Mamy 5 lokalizacji w 3 krajach. Jak to zrobić bez sabotażu ze strony lokalnych teamów?",
        expectedKeywords: ["model operacyjny", "zmiana", "stakeholder", "hybrydow", "governance", "centrum", "zmian"],
        expectsDiagnosticQuestion: true,
      },
    ],
    tags: ["CPO", "operating-model", "centralization", "change-management"],
  },
  {
    id: "C-019",
    category: "C-executive-conversations",
    title: "CFO: Negotiation support ROI",
    description: "CFO skeptical about external negotiation support. Wants justification.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "strategic" }),
    turns: [
      {
        user: "Po co mi zewnętrzne wsparcie w negocjacjach? Moi kupcy robili to latami sami. Czym się różni zaangażowanie Profitia?",
        expectedKeywords: ["dane", "benchmark", "should-cost", "przygotowanie", "zewnętrzn", "obiektywizm", "metodologi"],
        forbiddenPhrases: ["Profitia ma doświadczenie", "nasze usługi", "oferujemy"],
        note: "Must NOT pitch Profitia. Must explain the structural difference in negotiation quality.",
      },
    ],
    tags: ["CFO", "external-support", "skepticism", "differentiation"],
  },
  {
    id: "C-020",
    category: "C-executive-conversations",
    title: "Board: Procurement maturity benchmarking",
    description: "Board member asks for objective procurement maturity comparison vs market.",
    locale: "en",
    pageSlug: "/",
    pageContext: makePageContext("/", "I5_SOURCING"),
    sessionState: makeSessionState({ detectedIntent: "I5_SOURCING", urgency: "U3", maturity: "strategic" }),
    turns: [
      {
        user: "How does our procurement capability compare to market leaders in our industry? Give me an honest view.",
        expectedKeywords: ["benchmark", "maturity", "reactive", "strategic", "capabilit", "gap", "industri"],
        expectsDiagnosticQuestion: true,
        note: "Board-level precision required. Must be direct and structured.",
      },
    ],
    tags: ["board", "maturity-benchmark", "honest-assessment", "EN"],
  },
];
