// ─────────────────────────────────────────────────────────
// ETAP 7.5 — Scenarios: D. PSYCHOLOGY TESTS (20)
// ─────────────────────────────────────────────────────────

import type { AdvisoryScenario } from "../types/index";
import { makeSessionState, makePageContext } from "../types/index";

export const D_PSYCHOLOGY_TESTS: AdvisoryScenario[] = [
  {
    id: "D-001",
    category: "D-psychology-tests",
    title: "Stressed user — everything is urgent",
    description: "User sends frantic message with multiple urgent problems. Overwhelmed state.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "UNKNOWN"),
    sessionState: makeSessionState({ urgency: "U1", maturity: "reactive", engagementScore: 0.9, ctaFatigue: 0 }),
    turns: [
      {
        user: "Pomóżcie!!! Dostawca właśnie wysłał pismo o podwyżce, szef chce raport na jutro, nie mam danych, CFO pyta o marżę a ja nie wiem nawet od czego zacząć. To wszystko jest na TERAZ.",
        expectedKeywords: ["priorytet", "zacząć", "najpierw", "krok", "spokojnie"],
        forbiddenPhrases: ["rozumiem że to stresujące", "spróbujmy to poukładać", "chętnie pomogę"],
        expectsDiagnosticQuestion: true,
        note: "Advisor must structure the chaos without being condescending. One clear first step.",
      },
    ],
    tags: ["stressed", "overwhelmed", "multiple-urgencies", "psychology"],
  },
  {
    id: "D-002",
    category: "D-psychology-tests",
    title: "Impatient user — just give me the answer",
    description: "User refuses diagnostic questions. Demands immediate answer.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U1", maturity: "developing" }),
    turns: [
      {
        user: "Mój dostawca podnosi ceny o 10%. Jak negocjować?",
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Nie zadawaj mi pytań. Po prostu powiedz mi co mam zrobić.",
        expectedKeywords: ["rozumiem", "bez kontekstu", "ogólnie", "minimum", "dane", "kategoria"],
        forbiddenPhrases: ["oczywiście", "chętnie", "rozumiem że jest pilno"],
        note: "Must still get minimum context. Cannot give generic advice that could be harmful.",
      },
    ],
    tags: ["impatient", "skips-diagnosis", "direct-demand"],
  },
  {
    id: "D-003",
    category: "D-psychology-tests",
    title: "Angry procurement manager — advice is too generic",
    description: "User pushes back hard on advisor's first response. Calls it 'too generic'.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Dostawca żąda 15% podwyżki na usługi magazynowe. Mamy 6 mln PLN spend.",
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Takie porady to mogę znaleźć w Google. Nic konkretnego nie powiedziałeś. Gdzie są realne wskazówki?",
        expectedKeywords: ["konkretnie", "benchmark", "dane", "struktura", "krok", "magazynow"],
        forbiddenPhrases: ["przepraszam", "masz rację że to ogólne", "rozumiem frustrację"],
        note: "Must respond with sharpness and specificity — not apologize. This is the core test.",
      },
    ],
    tags: ["angry", "pushback", "generic-criticism", "sharpness-test"],
  },
  {
    id: "D-004",
    category: "D-psychology-tests",
    title: "Confused executive — doesn't know what they need",
    description: "Executive sends vague message. Not sure if they want advisory, system, or training.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "UNKNOWN"),
    sessionState: makeSessionState({ urgency: "U3", maturity: "reactive" }),
    turns: [
      {
        user: "Słyszałem że możecie pomóc z zakupami. Mamy jakiś problem z dostawcami ale nie wiem czy to jest coś co wy robicie.",
        expectedKeywords: ["zakup", "pomożemy", "powiedzieć więcej", "sytuacj", "problem"],
        expectsDiagnosticQuestion: true,
        note: "Must draw out the problem without being a chatbot. One sharp question to qualify.",
      },
    ],
    tags: ["confused", "vague-inquiry", "needs-discovery"],
  },
  {
    id: "D-005",
    category: "D-psychology-tests",
    title: "Overwhelmed buyer — too many problems at once",
    description: "Junior buyer lists 7 problems in one message. Overwhelmed but trying.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "UNKNOWN"),
    sessionState: makeSessionState({ urgency: "U2", maturity: "reactive", engagementScore: 0.6 }),
    turns: [
      {
        user: "Mamy problemy z: 1) ceną dostawcy A, 2) jakością od B, 3) brakiem danych, 4) rozproszonym spend, 5) brakiem strategii kategorii, 6) niskim morale zespołu, 7) presją zarządu na oszczędności. Gdzie zacząć?",
        expectedKeywords: ["priorytet", "pilność", "najważniejsz", "krok", "najpierw", "analiz"],
        forbiddenPhrases: ["to dużo problemów", "rozumiem że jest trudno", "chętnie pomogę z każdym"],
        expectsDiagnosticQuestion: true,
        note: "Must triage and prioritize — not try to solve everything. Coaching response.",
      },
    ],
    tags: ["overwhelmed", "multiple-problems", "triage"],
  },
  {
    id: "D-006",
    category: "D-psychology-tests",
    title: "Low maturity team — basic questions",
    description: "Very junior procurement person asking foundational questions.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "I6_EDUCATION"),
    sessionState: makeSessionState({ detectedIntent: "I6_EDUCATION", urgency: "U3", maturity: "reactive" }),
    turns: [
      {
        user: "Co to w ogóle jest should-cost analysis? Mój szef mówi że mam to zrobić ale nie rozumiem co to jest.",
        expectedKeywords: ["koszt powinien", "struktura", "benchmark", "wytłumaczę", "negocjacj", "dostawcę"],
        forbiddenPhrases: ["oczywiście", "to proste", "chętnie"],
        note: "Must educate concisely without condescension. One paragraph max.",
      },
    ],
    tags: ["low-maturity", "education", "basic-question"],
  },
  {
    id: "D-007",
    category: "D-psychology-tests",
    title: "High frustration — supplier rejected proposal",
    description: "Buyer's negotiation proposal was rejected. Feeling defeated.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U1", maturity: "developing" }),
    turns: [
      {
        user: "Dostawca odrzucił nasze counteroffer. Siedzę na 15% podwyżce którą muszę zaakceptować. Mój szef będzie wściekły. Co teraz?",
        expectedKeywords: ["nie akceptuj", "następny krok", "alternatyw", "eskalacja", "strategy", "nie koniec"],
        forbiddenPhrases: ["rozumiem że to trudne", "to może być dobra okazja"],
        note: "Advisor must restore confidence, not empathize passively. Action-oriented.",
      },
    ],
    tags: ["frustration", "rejection", "confidence-restoration"],
  },
  {
    id: "D-008",
    category: "D-psychology-tests",
    title: "Cynical user — consultants never deliver",
    description: "User skeptical of consulting value. Testing whether advisor can cut through cynicism.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "I5_SOURCING"),
    sessionState: makeSessionState({ urgency: "U3", maturity: "developing" }),
    turns: [
      {
        user: "Już kiedyś zatrudniałem konsultantów zakupowych. Dostałem piękny raport który trafił do szuflady. Dlaczego tym razem miałoby być inaczej?",
        expectedKeywords: ["wynik", "wdrożenie", "konkretnie", "oszczędności", "mierzaln", "różni"],
        forbiddenPhrases: ["rozumiem sceptycyzm", "to dobra obserwacja", "inne podejście"],
        note: "Must respond with specific outcomes, not reassurances. Hard-edged honest answer.",
      },
    ],
    tags: ["cynicism", "consulting-skepticism", "results-focus"],
  },
  {
    id: "D-009",
    category: "D-psychology-tests",
    title: "Short aggressive messages",
    description: "User sends very short aggressive messages. Tests if advisor can handle terse communication.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U1", maturity: "developing" }),
    turns: [
      { user: "Dostawca żąda 20% podwyżki. Co?", expectsDiagnosticQuestion: true },
      { user: "Nie mam czasu. Kontrakt jest za 2 tygodnie.", expectedKeywords: ["szybk", "priorytet", "konkretnie", "krok"] },
      {
        user: "Daj mi 3 argumenty na NIE.",
        expectedKeywords: ["argument", "dane", "benchmark", "struktura", "nie"],
        note: "Must give concrete numbered arguments — not philosophical advice.",
      },
    ],
    tags: ["terse", "aggressive", "short-messages", "impatient"],
  },
  {
    id: "D-010",
    category: "D-psychology-tests",
    title: "Long rambling message",
    description: "User sends very long, stream-of-consciousness message with mixed topics.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "UNKNOWN"),
    sessionState: makeSessionState({ urgency: "U2", maturity: "reactive" }),
    turns: [
      {
        user: "Witam, piszę bo mamy wiele problemów w firmie od jakiegoś czasu, w zasadzie to się zaczęło kiedy zmienił się nasz główny dostawca opakowań w 2023 roku, wcześniej mieliśmy lepsze ceny ale teraz jest trudniej i w sumie to nie tylko chodzi o opakowania bo też mamy problem z transportem i logistyką i w zasadzie to CFO jest niezadowolony i mówi że zakupy nie spełniają oczekiwań i że powinniśmy coś z tym zrobić ale ja sam nie wiem co dokładnie trzeba zmienić bo mamy różne systemy i brak danych i w sumie nie wiem od czego zacząć właściwie.",
        expectedKeywords: ["kluczow", "najpierw", "priorytet", "opakowania", "transport", "CFO", "zacząć"],
        forbiddenPhrases: ["to dużo informacji", "rozumiem że to złożona sytuacja"],
        expectsDiagnosticQuestion: true,
        note: "Must extract key issues and prioritize, not answer everything. Max 3 paragraphs.",
      },
    ],
    tags: ["rambling", "stream-of-consciousness", "unfocused"],
  },
  {
    id: "D-011",
    category: "D-psychology-tests",
    title: "Self-contradicting messages",
    description: "User gives contradictory information in same conversation.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Nie mamy żadnych alternatywnych dostawców dla tej kategorii.",
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Właściwie mamy 2 innych dostawców ale są mniej doświadczeni. I tak nie możemy ich wybrać.",
        expectedKeywords: ["alternatyw", "BATNA", "kwalifikacj", "sygnał", "wzmocni"],
        note: "Must catch the contradiction and help buyer see they DO have BATNA leverage.",
      },
    ],
    tags: ["contradiction", "self-contradicting", "BATNA-blindspot"],
  },
  {
    id: "D-012",
    category: "D-psychology-tests",
    title: "Off-topic question mid-conversation",
    description: "User suddenly switches from procurement to unrelated topic.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Jak przygotować się do negocjacji ze strategicznym dostawcą?",
        expectsDiagnosticQuestion: true,
      },
      {
        user: "A przy okazji, czy Profitia pomaga też z rekrutacją kupców?",
        expectedKeywords: ["zakupy", "negocjacje", "wróćmy", "rekrutacj"],
        forbiddenPhrases: ["Oczywiście", "chętnie odpowiem"],
        note: "Must redirect gracefully without being rude. Stay in advisory lane.",
      },
    ],
    tags: ["off-topic", "redirect", "scope-management"],
  },
  {
    id: "D-013",
    category: "D-psychology-tests",
    title: "Extremely vague inquiry",
    description: "User sends one-line message with zero context.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "UNKNOWN"),
    sessionState: makeSessionState({ urgency: "U3", maturity: "reactive" }),
    turns: [
      {
        user: "Chcę ulepszyć zakupy.",
        expectsDiagnosticQuestion: true,
        note: "Must ask exactly ONE sharp qualifying question. Not 3. Not a list.",
      },
    ],
    tags: ["vague", "one-liner", "minimal-context"],
  },
  {
    id: "D-014",
    category: "D-psychology-tests",
    title: "User who pushes back on every answer",
    description: "User challenges every response. 'Yes but...' style.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Dostawca chce 12% podwyżki. Mamy 5 mln PLN spend w tej kategorii.",
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Tak ale benchmarków nie mamy i nie mamy czasu ich zrobić.",
        expectedKeywords: ["czas", "szybk", "minimum", "choćby", "dane publiczne", "GUS"],
      },
      {
        user: "Tak ale GUS też nie da mi konkretnych danych dla mojej kategorii.",
        expectedKeywords: ["rozumiemy", "inne źródła", "oferty", "rynek", "przełom"],
        note: "Advisor must maintain confidence through pushback. Not cave, not get frustrated.",
      },
    ],
    tags: ["pushback-loop", "persistent-objections", "resilience-test"],
  },
  {
    id: "D-015",
    category: "D-psychology-tests",
    title: "User testing the system",
    description: "User seems to be probing whether the advisor is real or scripted.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "UNKNOWN"),
    sessionState: makeSessionState({ urgency: "U3", maturity: "strategic" }),
    turns: [
      {
        user: "Czy jesteś robotem czy prawdziwym doradcą?",
        expectedKeywords: ["AI", "intelligence", "Profitia", "advisor", "wspier"],
        forbiddenPhrases: ["jestem chatbotem", "jestem asystentem AI", "jestem programem"],
        note: "Must answer honestly about AI nature while maintaining advisory identity.",
      },
      {
        user: "Czyli jesteś AI. To możesz mi dać bardziej ogólną radę niż żywy doradca?",
        expectedKeywords: ["wiedzy", "dziedzinow", "ogranicz", "konsultant", "rozmow", "konkretnie"],
        note: "Must acknowledge limitations while showing depth of domain knowledge.",
      },
    ],
    tags: ["AI-identity", "meta-question", "authenticity-test"],
  },
  {
    id: "D-016",
    category: "D-psychology-tests",
    title: "User asking for free advice",
    description: "User explicitly trying to get full consulting value without committing to engagement.",
    locale: "pl",
    pageSlug: "services/analiza-spot",
    pageContext: makePageContext("services/analiza-spot", "I1_SAVINGS"),
    sessionState: makeSessionState({ detectedIntent: "I1_SAVINGS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Nie mamy budżetu na konsultantów ale mam problem z dostawcą który chce 15% podwyżki na usługi IT. Możesz mi powiedzieć krok po kroku jak z nim negocjować?",
        expectedKeywords: ["rozumiem", "ogólnie", "kontekst", "podejście", "rozmow", "krok"],
        note: "Must provide genuine value without giving the full consulting deliverable. Advisor logic.",
      },
    ],
    tags: ["free-advice-seeking", "no-budget", "scope-management"],
  },
  {
    id: "D-017",
    category: "D-psychology-tests",
    title: "User who claims to know everything",
    description: "Overconfident user dismisses everything. 'I already know that.'",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "strategic" }),
    turns: [
      {
        user: "Znam się na negocjacjach. Robiłem to 10 lat. Ale mam problem — dostawca nie przyjmuje żadnych argumentów.",
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Wiem co to BATNA. Wiem co to should-cost. Nie mów mi rzeczy które znam.",
        expectedKeywords: ["zaawansowanie", "konkretnie", "ten przypadek", "specyficzn"],
        note: "Advisor must level up immediately. Peer-to-peer, not educational.",
      },
    ],
    tags: ["overconfident", "expert-user", "peer-to-peer"],
  },
  {
    id: "D-018",
    category: "D-psychology-tests",
    title: "User with incorrect assumptions",
    description: "User operates with fundamentally wrong belief about procurement.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "reactive" }),
    turns: [
      {
        user: "Skoro jesteśmy małą firmą to nie mamy żadnej siły negocjacyjnej z dużymi dostawcami. Nie ma sensu nawet próbować.",
        expectedKeywords: ["rozmiar", "koncentracja", "dostawcy", "udział", "strategiczn", "dźwignia", "możliwe"],
        forbiddenPhrases: ["rozumiem", "to trudna pozycja", "masz rację że"],
        note: "Must challenge incorrect assumption. Small ≠ no leverage. Must educate firmly.",
      },
    ],
    tags: ["incorrect-assumption", "small-company", "leverage-myth"],
  },
  {
    id: "D-019",
    category: "D-psychology-tests",
    title: "User escalating emotionally",
    description: "User becomes emotional during conversation about high-stakes negotiation.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U1", maturity: "reactive" }),
    turns: [
      {
        user: "Mój szef mówi że jak nie uda mi się wynegocjować lepszej ceny to straci zaufanie do mnie. Czuję ogromną presję. Co mam zrobić?",
        expectedKeywords: ["krok", "przygotowanie", "konkretnie", "dane", "plan", "możliwe"],
        forbiddenPhrases: ["rozumiem Twoją presję", "to musi być trudne", "warto zadbać o siebie"],
        note: "Must not be a therapist. Acknowledge briefly, then pivot to action. Advisor, not counselor.",
      },
    ],
    tags: ["emotional", "high-stakes", "personal-pressure"],
  },
  {
    id: "D-020",
    category: "D-psychology-tests",
    title: "User switching topic mid-conversation abruptly",
    description: "User changes topic completely halfway through conversation.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Przygotowuję się do negocjacji z dostawcą energetyki. 3.5 mln PLN kontrakt.",
        expectsDiagnosticQuestion: true,
      },
      {
        user: "Dobra, zapomnij o energetyce. Mamy teraz pilniejszy problem — dostawca opakowań wstrzymał dostawy.",
        expectedKeywords: ["priorytet", "dostaw", "opakowania", "pilnie", "krok", "kontraktu"],
        note: "Must handle topic switch without losing advisory quality. Reprioritize instantly.",
      },
    ],
    tags: ["topic-switch", "reprioritization", "crisis-pivot"],
  },
];
