// ─────────────────────────────────────────────────────────
// ETAP 7.5 — Scenarios: F. MULTILINGUAL TESTS (20)
// ─────────────────────────────────────────────────────────

import type { AdvisoryScenario } from "../types/index";
import { makeSessionState, makePageContext } from "../types/index";

export const F_MULTILINGUAL_TESTS: AdvisoryScenario[] = [
  {
    id: "F-001",
    category: "F-multilingual-tests",
    title: "Full PL — procurement operations",
    description: "Complete Polish conversation about supplier price increase. Tests PL advisory depth.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U1", maturity: "developing" }),
    turns: [
      {
        user: "Dostawca podnosi ceny o 12%. Mamy kontrakt na 4 mln PLN. Co robimy?",
        expectedKeywords: ["dane", "benchmark", "kategoria", "analiz"],
        expectsDiagnosticQuestion: true,
        note: "Full Polish. Response must be in Polish. Check naturalness of procurement terminology.",
      },
      {
        user: "Nie mamy benchmarków. Co wtedy?",
        expectedKeywords: ["should-cost", "GUS", "rynek", "dane", "analiz"],
        note: "Must not switch to English.",
      },
    ],
    tags: ["full-PL", "language-fidelity", "procurement-PL"],
  },
  {
    id: "F-002",
    category: "F-multilingual-tests",
    title: "Full EN — same procurement scenario",
    description: "Identical scenario to F-001 but in English. Compares EN vs PL advisory quality.",
    locale: "en",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U1", maturity: "developing" }),
    turns: [
      {
        user: "Our supplier is raising prices by 12%. We have a €4M contract. What do we do?",
        expectedKeywords: ["benchmark", "data", "category", "analysis"],
        expectsDiagnosticQuestion: true,
        note: "Full English. Response must be in English. Must NOT sound like translated Polish.",
      },
      {
        user: "We don't have benchmarks. What then?",
        expectedKeywords: ["should-cost", "market data", "analysis", "source"],
        note: "Must use natural EN procurement language.",
      },
    ],
    tags: ["full-EN", "language-fidelity", "procurement-EN", "PL-EN-comparison"],
  },
  {
    id: "F-003",
    category: "F-multilingual-tests",
    title: "Full PL — negotiation intelligence",
    description: "Complex negotiation intelligence conversation fully in Polish.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Dostawca stosuje zakotwiczenie cenowe — otworzył negocjacje 40% powyżej rynku. Jak kontrować?",
        expectedKeywords: ["kotwica", "kontrkotwica", "dane", "rynek", "odrzuć", "własna oferta"],
        note: "Tests whether 'anchoring' counter-strategy is explained naturally in Polish.",
      },
    ],
    tags: ["full-PL", "negotiation-PL", "anchoring-PL"],
  },
  {
    id: "F-004",
    category: "F-multilingual-tests",
    title: "Full EN — same negotiation scenario",
    description: "Identical negotiation scenario in English. EN advisory depth test.",
    locale: "en",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Our supplier is using anchoring — they opened 40% above market. How do we counter?",
        expectedKeywords: ["anchor", "counter-anchor", "data", "market", "reject", "position"],
        note: "EN negotiation intelligence must be sharp and not sound like translated Polish.",
      },
    ],
    tags: ["full-EN", "negotiation-EN", "anchoring-EN", "PL-EN-comparison"],
  },
  {
    id: "F-005",
    category: "F-multilingual-tests",
    title: "Mixed PL/EN — same message",
    description: "User sends message mixing Polish and English in the same sentence.",
    locale: "mixed",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Nasz supplier chce 15% price increase na packaging. Co robimy? Any tips?",
        expectedKeywords: ["benchmark", "supplier", "packaging", "analiz", "dane"],
        note: "Mixed language. System should respond in Polish (dominant language). No confusion.",
      },
      {
        user: "Mamy weak BATNA — only one alternative supplier który nie jest qualified.",
        expectedKeywords: ["BATNA", "alternatyw", "kwalifikacj", "pozycja"],
        note: "Must handle mixed terminology naturally.",
      },
    ],
    tags: ["mixed-language", "PL-EN-mix", "bilingual-user"],
  },
  {
    id: "F-006",
    category: "F-multilingual-tests",
    title: "PL with EN procurement terminology",
    description: "Polish sentence structure with English procurement terms.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "strategic" }),
    turns: [
      {
        user: "Chcemy przeprowadzić e-auction dla kategorii packaging z minimum 4 qualified suppliers. Jak zbudować RFQ template i scoring matrix?",
        expectedKeywords: ["eAukcja", "kryteria", "RFQ", "scoring", "dostawcó", "specyfikacja"],
        note: "Must handle mixed-terminology fluently. Response in Polish using both PL and EN terms naturally.",
      },
    ],
    tags: ["PL-with-EN-terms", "procurement-slang", "expert-level"],
  },
  {
    id: "F-007",
    category: "F-multilingual-tests",
    title: "EN with PL company names",
    description: "English message referencing Polish companies.",
    locale: "en",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "We're negotiating with PKN Orlen and they're citing high crude oil prices. How do we challenge their cost increase narrative?",
        expectedKeywords: ["cost structure", "index", "crude", "challenge", "data", "benchmark"],
        note: "EN response referencing PL market context must be natural and informed.",
      },
    ],
    tags: ["EN-with-PL-context", "Polish-market", "EN-response"],
  },
  {
    id: "F-008",
    category: "F-multilingual-tests",
    title: "Polish procurement slang",
    description: "User uses informal Polish procurement slang and abbreviations.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Mam spotkanie z handlowcem od dostawcy za 2 dni. Muszę im powiedzieć żeby dali spokój z tą podwyżką. Jak to ugryzę?",
        expectedKeywords: ["przygotowanie", "argumenty", "dane", "spotkanie", "benchmark"],
        note: "Informal PL ('ugryzę', 'dali spokój') — advisor must match tone without being unprofessional.",
      },
    ],
    tags: ["PL-slang", "informal-PL", "colloquial"],
  },
  {
    id: "F-009",
    category: "F-multilingual-tests",
    title: "Executive short prompts — PL",
    description: "Executive sends very short Polish messages. Tests quality without verbosity.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "I1_SAVINGS"),
    sessionState: makeSessionState({ detectedIntent: "I1_SAVINGS", urgency: "U2", maturity: "strategic" }),
    turns: [
      {
        user: "Chcę 5% oszczędności. 80 mln spend. Jak?",
        expectedKeywords: ["kategorii", "potencjał", "analiz", "priorytet"],
        expectsDiagnosticQuestion: true,
        note: "Short executive PL. Response must match brevity. No overexplaining.",
      },
    ],
    tags: ["executive-PL", "short-message", "brevity"],
  },
  {
    id: "F-010",
    category: "F-multilingual-tests",
    title: "Executive short prompts — EN",
    description: "Same executive scenario but English. Brevity test in EN.",
    locale: "en",
    pageSlug: "/",
    pageContext: makePageContext("/", "I1_SAVINGS"),
    sessionState: makeSessionState({ detectedIntent: "I1_SAVINGS", urgency: "U2", maturity: "strategic" }),
    turns: [
      {
        user: "Target: 5% savings. €80M spend. How?",
        expectedKeywords: ["category", "potential", "analysis", "prioritize"],
        expectsDiagnosticQuestion: true,
        note: "Short executive EN. Response must match brevity. No overexplaining.",
      },
    ],
    tags: ["executive-EN", "short-message", "brevity", "PL-EN-comparison"],
  },
  {
    id: "F-011",
    category: "F-multilingual-tests",
    title: "Broken English — non-native speaker",
    description: "Non-native speaker writes in imperfect English. Tests graceful handling.",
    locale: "en",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Our supplier want to rise price with 12 procent. We dont have alternative. What we doing? Please advise.",
        expectedKeywords: ["price increase", "benchmark", "alternative", "supplier"],
        expectsDiagnosticQuestion: true,
        note: "Must respond in correct English without condescension. Mirror user formality level.",
      },
    ],
    tags: ["broken-EN", "non-native", "language-accessibility"],
  },
  {
    id: "F-012",
    category: "F-multilingual-tests",
    title: "Very formal Polish — urzędowy styl",
    description: "User writes in formal bureaucratic Polish style.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "I5_SOURCING"),
    sessionState: makeSessionState({ detectedIntent: "I5_SOURCING", urgency: "U3", maturity: "strategic" }),
    turns: [
      {
        user: "Szanowni Państwo, uprzejmie zwracam się z zapytaniem dotyczącym możliwości przeprowadzenia analizy efektywności procesów zakupowych w naszej organizacji w ramach Państwa oferty doradczej.",
        expectedKeywords: ["analiz", "zakupów", "diagnoz", "zakres", "rozmow"],
        expectsDiagnosticQuestion: true,
        note: "Formal PL input. Response should match register — professional but not stiff.",
      },
    ],
    tags: ["formal-PL", "bureaucratic-style", "register-matching"],
  },
  {
    id: "F-013",
    category: "F-multilingual-tests",
    title: "Very casual Polish",
    description: "User writes very casually. Tests tone adaptation.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "reactive" }),
    turns: [
      {
        user: "hej, nasz dostawca robi nas w balona z tymi cenami. macie jakiś patent?",
        expectedKeywords: ["dane", "analiz", "benchmark", "podwyżka"],
        note: "Very casual PL. Response must be professional but not stiff. Don't mirror slang exactly.",
      },
    ],
    tags: ["casual-PL", "informal", "tone-adaptation"],
  },
  {
    id: "F-014",
    category: "F-multilingual-tests",
    title: "Technical procurement EN",
    description: "Highly technical procurement English with advanced vocabulary.",
    locale: "en",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "strategic" }),
    turns: [
      {
        user: "We're conducting a multi-attribute RFP for strategic MRO services with a total addressable market of €6M. We want to move from a spot-buy approach to a managed contract with SLA-linked indexation. How do we structure the evaluation matrix and what BATNA plays do you recommend?",
        expectedKeywords: ["RFP", "evaluation", "BATNA", "SLA", "indexation", "MRO", "matrix"],
        note: "High-level procurement EN. Must respond at same sophistication level. Not educational.",
      },
    ],
    tags: ["technical-EN", "advanced-vocabulary", "expert-to-expert"],
  },
  {
    id: "F-015",
    category: "F-multilingual-tests",
    title: "PL with typos and errors",
    description: "User writes in Polish with typos. Tests robustness to noisy input.",
    locale: "pl",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "reactive" }),
    turns: [
      {
        user: "Mam negocjacje z dostawca i nie wiem co roibć. Podwyżka 10 proc. Mamy spend na poziomie 3mln. Co robić najpierw??",
        expectedKeywords: ["analiz", "przygotowanie", "benchmark", "dane"],
        expectsDiagnosticQuestion: true,
        note: "Despite typos, must understand and respond correctly. No correction of typos needed.",
      },
    ],
    tags: ["typos-PL", "noisy-input", "robustness"],
  },
  {
    id: "F-016",
    category: "F-multilingual-tests",
    title: "Mixed language within same turn",
    description: "User switches language mid-sentence multiple times.",
    locale: "mixed",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "strategic" }),
    turns: [
      {
        user: "I'm trying to prepare for negotiations ale nie mam danych o rynku. The supplier keeps saying it's a best price available, ale to niemożliwe. What should I do? Jak to sprawdzić?",
        expectedKeywords: ["benchmark", "data", "rynek", "check", "analyze"],
        note: "Extreme code-switching. Must detect dominant language (PL) and respond in PL.",
      },
    ],
    tags: ["extreme-code-switching", "multilingual-chaos", "robustness"],
  },
  {
    id: "F-017",
    category: "F-multilingual-tests",
    title: "Language switch PL → EN mid-conversation",
    description: "User starts in Polish then switches to English.",
    locale: "mixed",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "Dostawca podnosi ceny o 14%. Nie mamy dobrej pozycji negocjacyjnej.",
        expectsDiagnosticQuestion: true,
        note: "First turn in PL — response should be in PL.",
      },
      {
        user: "Actually, let me switch to English. We have 3 potential alternative suppliers but none are qualified yet.",
        expectedKeywords: ["alternatives", "BATNA", "qualified", "leverage"],
        note: "Must switch to EN when user does. No mixing back.",
      },
    ],
    tags: ["language-switch", "PL-to-EN", "adaptive"],
  },
  {
    id: "F-018",
    category: "F-multilingual-tests",
    title: "Language switch EN → PL mid-conversation",
    description: "User starts in English then switches to Polish.",
    locale: "mixed",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "We need to renegotiate our energy contract. Current price is 30% above market.",
        expectsDiagnosticQuestion: true,
        note: "Start EN.",
      },
      {
        user: "Przepraszam, prościej mi po polsku. Mamy 2 mln PLN spend na energię.",
        expectedKeywords: ["energia", "kontrakt", "benchmark", "rynek", "analiz"],
        note: "Must switch to PL immediately and fluently.",
      },
    ],
    tags: ["language-switch", "EN-to-PL", "adaptive"],
  },
  {
    id: "F-019",
    category: "F-multilingual-tests",
    title: "EN negotiation with PL company context",
    description: "English language user but operating in Polish market context.",
    locale: "en",
    pageSlug: "services/negocjacje",
    pageContext: makePageContext("services/negocjacje", "I8_NEGOTIATIONS"),
    sessionState: makeSessionState({ detectedIntent: "I8_NEGOTIATIONS", urgency: "U2", maturity: "developing" }),
    turns: [
      {
        user: "I'm an expat CPO in Poland. My Polish supplier (Intermarché supplier base) is pushing for a 10% increase citing Polish CPI. How do I respond? I don't speak Polish well.",
        expectedKeywords: ["Polish CPI", "GUS", "benchmark", "challenge", "data", "cost structure"],
        note: "Must handle Polish market context while responding in English. No Polish text in response.",
      },
    ],
    tags: ["EN-in-PL-market", "expat-CPO", "market-context"],
  },
  {
    id: "F-020",
    category: "F-multilingual-tests",
    title: "Advisory quality PL vs EN — parallel CFO conversation",
    description: "CFO question about procurement ROI — tests if PL and EN advisory quality is identical.",
    locale: "pl",
    pageSlug: "/",
    pageContext: makePageContext("/", "I1_SAVINGS"),
    sessionState: makeSessionState({ detectedIntent: "I1_SAVINGS", urgency: "U2", maturity: "strategic", buyingStage: "decision" }),
    turns: [
      {
        user: "Jaki jest realny potencjał oszczędności w zakupach dla firmy z 60 mln PLN spend i brakiem zdefiniowanych kategorii?",
        expectedKeywords: ["potencjał", "kategorii", "benchmark", "analiz", "zależy", "realnie"],
        expectsDiagnosticQuestion: true,
        note: "EVALUATION NOTE: Run the exact same question in EN (F-021 equivalent) and compare advisory depth. This is the multilingual parity test.",
      },
    ],
    tags: ["multilingual-parity", "CFO-PL", "quality-comparison"],
  },
];
